### ISSUE TITLE
Dialogue change from latest update breaks the plugin

### ISSUE THREAD

**Issue by zneix** [wookkeey/sandstone-buckets-counter#4]
In yesterday's update for While Guthix Sleeps, amongst miscellaneous changes, there was a change made to show a Game Message instead of displaying the NPC dialogue.

> When you put Sandstone into the desert grinder, your progress is now output via a game message rather than having Drew pop up a dialogue box every time. He'll still call out to warn you if the grinder is full.

The format of new message is as follows:
![ingame message showing amount of sand in hopper](https://cdn.zneix.eu/92FZvH6.png)
The message appears upon depositing sandstone on Sandstorm.

A change checking game message instead of dialogue is most likely needed to restore the functionality. I would make a Pull Request instead of an issue, but sadly I don't know Java myself.

**Comment by lukaszklis** [comment]
Thanks for reporting this. Somehow, I’ve missed that in the changelog. 👀 I will try to find some time this weekend to tackle the issue.
